
trigger:
- none

stages:
- stage: build
  displayName: building stage
  pool: 
   vmImage: ubuntu-latest
  
  jobs:
  - deployment: deploymentJob
    displayName: Deploy to VM
    environment: vm.vm1-demo
   
    strategy:
      runOnce:
          deploy:   
            steps:
                - checkout: self
                
                - task: NodeTool@0
                  inputs:
                    versionSource: 'spec'
                    versionSpec: '10.19.0'
                    checkLatest: true
                - task: UniversalPackages@0
                  inputs:
                    command: 'download'
                    downloadDirectory: '$(System.DefaultWorkingDirectory)'
                    feedsToUse: 'internal'
                    vstsFeed: '25fd97b3-0e67-4e99-be8d-ba6285589350/efceda07-3b0f-4f54-afed-1af0255edc55'
                    vstsFeedPackage: 'node-hello'
                    vstsPackageVersion: '1.*'