
name: Docker Image CI

on:
  push:
    branches: [ "devlopment" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
       docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{secrets.ENDPOINT}}

    - uses: azure/docker-login@v1
      with:
          login-server: yourACRname.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    - name: Extract first 5 characters of SHA
      run: |
        SHA_SHORT=$(echo "${{ github.sha }}" | cut -c 1-5)
        echo "SHA_SHORT=${SHA_SHORT}" >> $GITHUB_ENV
  
    - name: Build and push Docker image
      env:
        DOCKERTAG: ${{ env.SHA_SHORT }}
      run: |
        docker build -t ${{ secrets.ENDPOINT }}/trailuse:${DOCKERTAG} .
        docker push ${{ secrets.ENDPOINT }}/trailuse:${DOCKERTAG}
