
name: Docker Image CI

on:
  push:
    branches: [ "devlopment" ]


jobs:

  build:
    env:
        DOCKERTAG: ${{ github.sha | slice(0, 5) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
       docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} ${{secrets.ENDPOINT}}

    - uses: azure/docker-login@v1
      with:
          login-server: yourACRname.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
  
    - run: |
          docker build -t ${{secrets.ENDPOINT}}/trailuse:${{ env.DOCKERTAG }} .
          docker push ${{secrets.ENDPOINT}}/trailuse:${{ env.DOCKERTAG }}
